-- MySQL Script generated by MySQL Workbench
-- 06/06/16 13:04:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema search_on_role
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema search_on_role
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `search_on_role` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `search_on_role` ;

-- -----------------------------------------------------
-- Table `search_on_role`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `search_on_role`.`usuario` ;

CREATE TABLE IF NOT EXISTS `search_on_role`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `senha` VARCHAR(32) NULL COMMENT '',
  `email` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `usuariocolsenha` (`senha` ASC)  COMMENT '',
  UNIQUE INDEX `usuariocolemail_UNIQUE` (`email` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `search_on_role`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `search_on_role`.`roles` ;

CREATE TABLE IF NOT EXISTS `search_on_role`.`roles` (
  `idroles` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `preco` FLOAT NULL COMMENT '',
  `data` VARCHAR(60) NULL COMMENT '',
  `local` VARCHAR(100) NULL COMMENT '',
  `descricao` VARCHAR(500) NULL COMMENT '',
  `origID` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idroles`)  COMMENT '',
  INDEX `fk_roles_usuario_idx` (`origID` ASC)  COMMENT '',
  CONSTRAINT `fk_roles_usuario`
    FOREIGN KEY (`origID`)
    REFERENCES `search_on_role`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `search_on_role`.`dados_pessoais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `search_on_role`.`dados_pessoais` ;

CREATE TABLE IF NOT EXISTS `search_on_role`.`dados_pessoais` (
  `nome` VARCHAR(45) NULL COMMENT '',
  `sobrenome` VARCHAR(45) NULL COMMENT '',
  `data_nascimento` DATE NULL COMMENT '',
  `usuario_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`usuario_id`)  COMMENT '',
  INDEX `fk_dados_pessoais_usuario1_idx` (`usuario_id` ASC)  COMMENT '',
  CONSTRAINT `fk_dados_pessoais_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `search_on_role`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
